// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovlcmbbrucljpgvacqht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92bGNtYmJydWNsanBndmFjcWh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Mjc5MDYsImV4cCI6MjA2NjUwMzkwNn0.p526Xjh9WC4L8KhoXQWJK8J1Gg1oZxPHk9D7ifPbi08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);